version: '3.9'

services:
#  timescaledb:
#    image: timescale/timescaledb:latest-pg14
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgre$$$
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg_data:/opt/pgsql/data
#      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning